const emotions = [
  {
    id: 'love',
    label: '사랑',
    emoji: '🥰',
    image: '/emoji/1F970.svg',
    mood: 'love',
    context: '이 사랑은 나를 <br/>따뜻하게 해줄까,<br/>아프게 할까?',
  },
  {
    id: 'happiness',
    label: '행복',
    emoji: '🤭',
    image: '/emoji/1F92D.svg',
    mood: 'happiness',
    context: '지금 이 행복, <br/>진짜 내 마음일까?',
  },
  {
    id: 'thankful',
    label: '감사',
    emoji: '🤠',
    image: '/emoji/1F920.svg',
    mood: 'thankful',
    context: '지금 내가 감사한 것,<br/>잊지 말아야 할 건 뭘까?',
  },
  {
    id: 'patience',
    label: '인내',
    emoji: '😳',
    image: '/emoji/1F633.svg',
    mood: 'patience',
    context: '내가 참고 있는 건<br/>희망 때문일까, <br/>두려움 때문일까?',
  },
  {
    id: 'courage',
    label: '용기',
    emoji: '🤯',
    image: '/emoji/1F92F.svg',
    mood: 'courage',
    context: '도망치지 않고<br/>마주 보려는 이유는 뭘까?',
  },
  {
    id: 'faith',
    label: '신뢰',
    emoji: '🫡',
    image: '/emoji/1FAE1.svg',
    mood: 'faith',
    context: '이 믿음은 기대일까,<br/>두려움일까?',
  },
  {
    id: 'funny',
    label: '즐거움',
    emoji: '😝',
    image: '/emoji/1F61D.svg',
    mood: 'funny',
    context: '웃고는 있지만,<br/>진짜 괜찮은 걸까?',
  },
  {
    id: 'sadness',
    label: '슬픔',
    emoji: '😥',
    image: '/emoji/1F625.svg',
    mood: 'sadness',
    context: '이 슬픔은<br/>시간이 지나면 괜찮아질까?',
  },
  {
    id: 'failure',
    label: '실패',
    emoji: '😖',
    image: '/emoji/1F616.svg',
    mood: 'failure',
    context: '이 실패는 끝일까,<br/>다시 시작하라는 신호일까?',
  },
  {
    id: 'fear',
    label: '두려움',
    emoji: '😡',
    image: '/emoji/1F621.svg',
    mood: 'fear',
    context: '내가 두려워하는 건<br/>결과일까, 시작 자체일까?',
  },
  {
    id: 'anger',
    label: '분노',
    emoji: '🤬',
    image: '/emoji/1F92C.svg',
    mood: 'anger',
    context: '이 화는 정말 <br/>상대를 향한 걸까,<br/>내 안의 실망일까?',
  },
  {
    id: 'respect',
    label: '존중',
    emoji: '🫥',
    image: '/emoji/1FAE5.svg',
    mood: 'respect',
    context: '그래서? 나 자신은 <br/>존중하고 있는걸까?',
  },
];

export default emotions;